//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurance
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Insurance.Models;

    public partial class SeguroEntities : DbContext
    {
        public SeguroEntities()
            //: base("name=SeguroEntities")
            :base(Seguridad.GetSqlConnection("SeguroEntities"))
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<cliente_seguro> cliente_seguro { get; set; }
        public virtual DbSet<seguro> seguro { get; set; }

        public System.Data.Entity.DbSet<Insurance.Models.Cliente> Clientes { get; set; }
    }
}
